### ISSUE TITLE
Multithreading for the LiDAR and Camera on RPI

### ISSUE THREAD

**Issue by acarrou** [SJSURoboticsTeam/urc-intelligent-systems-2023#62]
To ensure the optimal performance of our system, we have implemented multithreading for the Lidar and camera modules on the Raspberry Pi. These devices generate a considerable amount of data that needs to be processed in real-time, which can be computationally intensive. With multithreading, we can continuously grab data without any interruptions, ensuring that we capture all necessary information accurately. Additionally, we have also applied a similar approach to the GPS module since obtaining location data continuously is essential. If you're interested, you can take a look at how we have implemented this feature.

**Comment by mrparmesan01** [comment]
To get this feature started, you will be implementing two threads to check how the data flow is handled. Once we test and see if this is functional and working, then create a thread pool that handles managing the way we work with threads. This is because each sensor may or may not be its thread. So, we want this thread pool to handle each sensor thread (referenced as the worker thread). So, we just either use an API/Framework for the corresponding devices and use those built-in thread handling features or if there are none for those devices. Then you would have to look into implementing one yourself.
